src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy

Addresses https://github.com/ben-manes/gradle-versions-plugin/issues/104.

Changed '/' to a system dependent separator.

---

.travis.yml

@ben-manes, you probably have to enable the build from https://travis-ci.org/ben-manes/gradle-versions-plugin, I don't have the required permissions.

add Travis build

---

build.gradle

Log more details when tests fail

Make test output more useful

---

.travis.yml
build.gradle

Travis will automatically build tags and deploy them to the Bintray repository

Deploy from travis

---

README.md
build.gradle
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionComparator.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy

@jochenberger 
Releasing is just incrementing the version, committing, and tagging it?

Support Gradle 4.0-rc-1 (fixes #162)

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionMapping.groovy

Also remove some unused imports

Fix type errors reported in Idea

---

.editorconfig
src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/DependenciesGroup.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Dependency.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Result.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionComparator.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/JavaLibrarySpec.groovy

Add `.editorconfig` to enforce formatting

Fix spacing and formatting

---

src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/AbstractReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/Reporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyStatus.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionComparator.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionMapping.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy

You can use `git log` or Github's "blame" to see past authors.

Remove authorship since it is open source

---

src/test/groovy/com/github/benmanes/gradle/versions/BaseSpecification.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/JavaLibrarySpec.groovy

- Use `.stripIndent()` for files
- Add spaces in between given/when/then, various smalls fixes

Clean up Tests

---

build.gradle
src/test/groovy/com/github/benmanes/gradle/versions/BaseSpecification.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/JavaLibrarySpec.groovy

Further test clean up

---

README.md
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Dependency.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyStatus.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
src/test/resources/maven/backport-util-concurrent/backport-util-concurrent-java12/3.1/backport-util-concurrent-java12-3.1.pom
src/test/resources/maven/com/google/guava/guava-parent/15.0/guava-parent-15.0.pom
src/test/resources/maven/com/google/guava/guava-parent/16.0-rc1/guava-parent-16.0-rc1.pom

Add project urls from pom to dependency reports

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy

Fixing issue highlighted in https://github.com/ben-manes/gradle-versions-plugin/issues/299 by @GFriedrich

299 only check nightly gradle release channel for nightly setting

---

README.md
examples/build.gradle
examples/kotlin/build.gradle.kts

Please have a look at the individual commit messages for the details.

Simpify and align Kotlin DSL example code

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy

Remove deprecated usage by newer variant

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionRulesWithCurrent.groovy

Fixes https://github.com/ben-manes/gradle-versions-plugin/pull/327#issuecomment-526015459

Check if original dependency exists in component selection

---

README.md

+ Before no versions were output.
+ This fix is based on the discussion in https://github.com/ben-manes/gradle-versions-plugin/issues/344.
---
@timja @jmfayard @bric3 Please review this fix.

Fix resolution strategy for Groovy.

---

build.gradle
src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy

let me know what version number you would like - 0.30.1 or 0.31.0

Html report fixes

---

build.gradle

Update com.thoughtworks.xstream:xstream to 1.4.14

---

src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy

- Add missing tests for `OutputFormatter`

Add missing tests for OutputFormatter

---

README.md
examples/kotlin/build.gradle.kts

https://docs.gradle.org/current/userguide/kotlin_dsl.html#kotdsl:containers

Use recommended Kotlin DSL syntax to prevent errors in IntelliJ

---

build.gradle

Bump xstream to 1.4.16

---

src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ResolutionStrategyWithCurrent.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy

- Remove redundant semicolons
- Replace method invoke with operator
- Make methods static
- Declare `getRowString(Dependency item)`

Refine code

---

README.md

Resolves #519
Also I added a table of content since the README is quite long

Readme: prevent bad copy/pasting and add a TOC

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/update-gradle-wrapper.yml

- Bump `setup-java` to v2
- Replace minor versions with major versions (will auto keep the latest)

Update github action versions

---

.github/workflows/build.yml
.github/workflows/deploy.yml

https://github.com/gradle/gradle-build-action

Optimize CI a bit

---

.gitignore

Based on @eygraber's comments here: https://github.com/ben-manes/gradle-versions-plugin/pull/600#pullrequestreview-956809546.
@ben-manes 
@eygraber

Update and clean up .gitignore

---

src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/VersionAvailable.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyStatus.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionMapping.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleReleaseChannel.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy

- More clean up
- Use of double quotes
- Use of `@Nullable` annotations
@ben-manes

more clean up, use of double quotes and @Nullable annotations

---

src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Dependency.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Result.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyStatus.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionMapping.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ResolutionStrategyWithCurrent.groovy

- Undo `.with { }`
- Undo `.each { }`
- Add more `@Nullable`
- More quotes
- Fix formatting
@ben-manes

more clean up

---

src/test/groovy/com/github/benmanes/gradle/versions/ComponentSelectionRuleSourceSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/ConstraintsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/JavaLibrarySpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/KotlinDslUsageSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy

fix various test warnings

---

api/build.gradle
build.gradle

Breaking down https://github.com/ben-manes/gradle-versions-plugin/pull/611
@ben-manes

optimize compile tasks

---

build.gradle

Breaking down https://github.com/ben-manes/gradle-versions-plugin/pull/611
@ben-manes

remove extra buildscan

---

build.gradle
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy

- Remove `JsonSlurper`
@ben-manes

remove JsonSlurper

---

.github/workflows/build.yml

- Make use of `GRADLE_OPTS`
@ben-manes

add GRADLE_OPTS

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependencyLatest.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependencyUnresolved.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Coordinate.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/VersionMapping.kt
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateResult.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.groovy

more types

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependenciesGroup.kt
src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy

remove JsonBuilder

---

api/build.gradle
build.gradle

- Trying to resolve error in https://github.com/ben-manes/gradle-versions-plugin/pull/622
@ben-manes

ensure kotlin support in both root and 'api'

---

src/test/groovy/com/github/benmanes/gradle/versions/ComponentSelectionRuleSourceSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/ConstraintsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/KotlinDslUsageSpec.groovy
src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy

use outcome to assert task success

---

api/build.gradle
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.kt
build.gradle

add ktlint to the build

---

build.gradle

Closes https://github.com/ben-manes/gradle-versions-plugin/issues/603
- Remove reports zip
- Remove tests jar
- Remove `mavenLocal()` - this is there by default
@ben-manes

clean up publshing

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/AbstractReporter.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/HtmlReporter.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/JsonReporter.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/XmlReporter.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependenciesGroup.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependencyLatest.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependencyOutdated.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependencyUnresolved.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/Result.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Coordinate.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyStatus.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/gradle/GradleReleaseChannel.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateResult.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateResults.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionRulesWithCurrent.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ResolutionStrategyWithCurrent.kt

clean up kotlin

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy

clean up DependencyUpdatesTask

---

build.gradle

Repro:
```
rm -rf  ~/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.42.0-SNAPSHOT
gradlew clean
gradlew build -x test // <- fails here
gradlew publishToMavenLocal -x test -s
cat ~/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.42.0-SNAPSHOT/gradle-versions-plugin-0.42.0-SNAPSHOT.pom
```
@ben-manes

fix broken publish

---

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy

replace groovy find with java8 find

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/BaseResolver.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/VersionMapping.kt
src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy

base resolver

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/BaseDependencyUpdates.kt
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy

base DependencyUpdates

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/BaseDependencyUpdatesTask.kt
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy

add BaseDependencyUpdatesTask

---

api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/BaseDependencyUpdates.kt
api/src/main/kotlin/com/github/benmanes/gradle/versions/updates/BaseDependencyUpdatesTask.kt
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy

more kotlin

---

gradle-versions-plugin/build.gradle

add my email to the repo

---

gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/ConstraintsSpec.groovy
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/KotlinDslUsageSpec.groovy

update gradle test versions

---

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/result/DependenciesGroup.kt
gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.kt
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy

Closes https://github.com/ben-manes/gradle-versions-plugin/issues/704
@ben-manes

fix #704 can't modify unresolved.dependencies

---

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdates.kt
gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.kt
gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt

Please have a look at the individual commit messages for the details.

Address inspection hints

---

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt

This fixes a mistake in PR #721 which used `allDependencies` here instead of `dependencies`, causing the inherited set always be empty, as a result of subtracting `allDependencies` from it.
This also prevents inherited kotlin deps from being included in the latest set, to avoid issues with having the original and modified dependencies both added to the copy.

Fix inherited collection to not be always empty

---

README.md
build.gradle
gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdates.kt
gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.kt
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy

Closes #782
This needs someone with actual knowledge of kotlin/groovy to look at it, but the logic itself and the test is written.

Allow filtering configurations

---

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/HtmlReporter.kt

Fix exceeded version reported in HTML report

---

gradle-versions-plugin/build.gradle

Update OKHttp to address security vulnerability.

---

.sdkmanrc

Use BellSoft Liberica JDK

---

README.md

Add Kotlin-DSL initscript example

---

.github/workflows/build.yml
build.gradle
gradle-versions-plugin/build.gradle
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/KotlinDependencyUpdatesSpec.groovy

Closes https://github.com/ben-manes/gradle-versions-plugin/issues/876
- Set Kotlin to 2.0.0
- Fix test with regex, it kept checking for Kotlin 2.0.0-Beta3
- Make the artifact names unique when uploading

Update Kotlin to 2.0.0 and fix broken build

---

settings.gradle.kts

References: https://docs.gradle.com/develocity/gradle-plugin/current/

Migrate from Gradle Enterprise to Gradle Develocity

---

build.gradle
gradle-versions-plugin/build.gradle
gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy

task -> task.register
all -> configureEach

Fix various warnings

---

gradle-versions-plugin/build.gradle

Closes https://github.com/ben-manes/gradle-versions-plugin/pull/839

plugin publish 1.2.1

---

gradle-versions-plugin/build.gradle
gradle.properties

Based on this conversation: https://github.com/ben-manes/gradle-versions-plugin/pull/879#discussion_r1696180571
Clean up after https://github.com/ben-manes/gradle-versions-plugin/pull/881

Clean up publishing

---

.github/dependabot.yml

Clean up dependabot.yml
@ben-manes

Clean up dependabot.yml

---

build.gradle.kts

Use JUnit platform

---

gradle/libs.versions.toml

Reverts ben-manes/gradle-versions-plugin#915

Revert "Bump com.squareup.moshi:moshi-kotlin from 1.12.0 to 1.13.0"

---

.github/workflows/build.yml

Make sure tests are counted and actually ran
See https://github.com/ben-manes/gradle-versions-plugin/pull/916
@ben-manes

Show test report

---

README.md

Follow up from https://github.com/deezer/caupain/discussions/34#discussioncomment-13455830

Add 'caupain' plugin link to README
