ben-manes/gradle-versions-plugin

gradle/wrapper/gradle-wrapper.properties, src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy
some quick fixes to get things working for our project... not sure if you want these changes or not...
=> make plugin work for multi-module android project with flatDirs

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
Hi,
I'm using gradle with the incubating 'configureOnDemand' option on, to achieve a speedup on the bigger projects.
Right now your plugin collects all dependencies from all projects in the current build and evaluates them with all repositories found anywhere. (Which I took to mean, the plugin should be applied to the root project only, otherwise stuff would be done redundantly)
WIth 'configureOnDemand' which is slated to become default, only needed projects are evaluated, meaning dependencies from children can only be read if they, by chance, were already configured.
This is the case for "gradle dependencyUpdates", but not for example for "gradle :dependencyUpdates"
The Gradle-Api allows calls to evaluationDependsOn...() inside task actions, which would make your plugin future proof. …
=> Have 'dependencyUpdates' task force evaluation of all childprojects

README.md
@ben-manes  Adding `plugins` block example to the `README.md` from this issue: https://github.com/ben-manes/gradle-versions-plugin/issues/108.
=> Add plugins block

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy, src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
The plugin does not run with Gradle 1.12 anymore. It also fails for earlier versions, but let's take one step at a time.
=> Fix for Gradle 1.12

README.md, src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
Make sure that the plug-in works with Gradle 4.1 and 4.2 (RC)
=> Test against the most recent releases

README.md
+ Avoid to maintain version information in `README.md`.
=> Use JCenter badge to inform about latest version.

README.md, src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/Reporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy
This PR holds the option to specify the name of the generated report file.
It doesn't use gradle's build-in report features but for now does the job.
Its closes #225 und was inspired by #48 
I thought about a way to test the `reportfileName` option, but without success. If you have something in your mind about it or any remarks on the changes feel free to write.
=> Custom filename for reports

README.md
The README doesn't mention how dependencyUpdates works in multi-project builds.
I was running it separately in each subproject, when what I actually wanted was just to
run it in the root project – but I wasn't aware the later worked. So, add some text to the
README so others aren't confused like I was.
=> Explain multi-project builds in README

README.md, examples/build.gradle, src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateResult.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateResults.groovy
The task property `checkForGradleUpdate` is defaulted to `true`. When set to `false` no check is performed, the plain text report, does not include the statement, and the json/xml report includes an enable flag, no version, and the reason.
Due to URLConnection defaulting to infinite timeout that can cause a hung build, the maximum connection and read timeouts are set to 15 seconds as a failsafe.
@aaronols @imanushin
=> Add flag to disable gradle update check (fixes #241)

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy
If running on Windows and if outputDir contains Unix separators, this
previous resulted in output like
Generated report file C:\Dev\oss-review-toolkit\model\build/dependencyUpdates\report.txt
Avoid the mixed use different separators by using a File instead of a
String here.
=> DependencyUpdatesReporter: Avoid output of mixed file separators

.gitignore, src/main/groovy/com/github/benmanes/gradle/versions/reporter/AbstractReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy, src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy, src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
Specify Gradle Release Channel when checking for Gradle updates.
Don't tell me that there is a RC release for Gradle when I only want final release versions of Gradle, e.g. don't show me:
```
Gradle updates:
- Gradle: [4.10.2 -> 5.0-rc-1]
```
=> 272 Specify Gradle Release Channel

README.md
FYI I found a cool trick to display the version number from the gradle Plugin Portal with a link to it.
=> README: known to work to 5.0 and gradlePluginPortal

README.md
Changes are required to exclude release candidates from OpenJFX and JAXB.
JAXB example: org.glassfish.jaxb:jaxb-bom:2.4.0-b180830.0438
OpenJFX example: org.openjfx:javafx:13-ea+2
=> Update example filters for OpenJFX and JAXB

README.md, src/test/groovy/com/github/benmanes/gradle/versions/KotlinDslUsageSpec.groovy
check that the syntax from `examples/kotlin/build.gradle.kts` actually works
=> tests: use modern Kotlin DSL usage

README.md
Extra escaping was added in c0b850601d74fd961762e6c8a80be980608714da and appears to break the matching; because $ is being treated as literal. Additionally, escaping the `\d` isn't necessary in a Groovy regex. 
Otherwise the new feature from #327 looks great - thanks!
=> Remove unnecessary/incorrect escaping in examples

README.md, examples/groovy/build.gradle, examples/kotlin/build.gradle.kts
Since the `.` matches every character in a RegEx, when you don't escape it every version is considered stable.
Also I added an optional `-r` to the end, because for example `jgit` uses this in version numbers of stable releases.
=> Escape . and - correctly in `isNonStable()` RegEx

examples/groovy/build.gradle, examples/kotlin/build.gradle.kts, src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy, src/test/groovy/com/github/benmanes/gradle/versions/JavaLibrarySpec.groovy
Dependency constraints can be used to set versions, and in particular can be used with the `java-platform` plugin to define all constraints in a single location. It would be convenient if these constraints were resolved by the plugin since then instead of resolving the dependencies of all projects in a monorepo controlled by a platform, just need to resolve a single project for better performance and simpler output.
I am wondering whether this feature should be restricted to projects with the java-platform plugin. Let me know if you have thoughts.
Reference
- https://docs.gradle.org/current/userguide/managing_transitive_dependencies.html#sec:dependency_constraints
- https://docs.gradle.org/current/userguide/java_platform_plugin.html
Fixes #350
=> Resolve dependency constraints.

src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy, src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy
- Groovy generates both `getFoo` and `isFoo` for boolean properties and Gradle doesn't like it anymore. So manually define `getFoo` to disable Groovy's generation
- All properties must be annotated, as a reminder for task authors I guess. Annotated the properties that can be `Closure` as `@Internal`
- Unit test now ensure we don't use deprecated stuff
Fixes #357
=> Work around Gradle 6.0 deprecations.

README.md
I kept it simple. Personally I searched for "refresh" on the README. I suppose other people might have the same issue.
=> Upgrade documentation with --refresh-dependencies flag

README.md
With a certain amount of Gradle projects, I became too lazy to add the plugin to each and every one of them. This is the solution I came up with, so I thought I'd share it. :-)
=> Add hint about how to add the plugin via an init script

README.md
The `current` Gradle docs don't have this section (and the whole site) anymore.
I'm not sure if this is an issue (at Gradle) or just placed somewhere else. But unfortunately I can't find it "somewhere else". Therefore I decided to replace the broken link with the latest working version. With that we have at least some kind of documentation , even if its maybe outdated.. 🙃 
Oh wait, while I'm write this is had another idea to search in the Gradle docs and... Tada:
https://docs.gradle.org/current/userguide/dynamic_versions.html#sec:component_selection_rules
I guess we can use the new link. Or should we point to a specific version like currently https://docs.gradle.org/6.5/userguide/dynamic_versions.html#sec:component_selection_rules? 🤔 
What do you think?
=> Replace broken link

README.md, examples/groovy/build.gradle, examples/kotlin/build.gradle.kts
Instead of configuring the task using the instance of it, use "named" function that returns TaskProvider.
Kotlin sample before changes: https://scans.gradle.com/s/agejecharcfa6/performance/configuration?focused=5&openScriptsAndPlugins=WzBd
Kotlin sample after changes: https://scans.gradle.com/s/mxv25ulispr4w/performance/configuration
Groovy sample before changes: https://scans.gradle.com/s/szcsxpdg6tfzu/performance/configuration?focused=5&openScriptsAndPlugins=WzBd
Groovy sample after changes: https://scans.gradle.com/s/xwxm6zqwivgew/performance/configuration
Closes https://github.com/ben-manes/gradle-versions-plugin/issues/407
=> Use lazy task configuration for dependencyUpdates

src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy
This resolves `okhttp-bom` dependency in @ZacSweers's https://github.com/ZacSweers/CatchUp project. The attributes are copied over so that the variant resolution is successful.
@Vampire @mike-ross-88 can you please test this in your projects as confirmation? I don't believe they are public for me to verify myself.
Simply checkout this branch, increment the build's version, and run `gradlew install`. In your project, you will want to include `mavenLocal()` as a plugin repository. Using the buildscript syntax versus plugins block seems to be needed. It should then run with the local artifact.
=> Copy dependency attributes for dynamic query (fixes #334)

build.gradle
- Use `jcenter` instead of `mavenCentral` in the `repositories` block
- Apply what plugins we can via `plugins` block
- Combine both `dependencies` blocks together
- `version` is deprecated in favor of `archiveVersion`
- `classifier` is deprecated in favor of `archiveClassifier`
- Rename `groovydocJar` to `docsJar` since it is the only docs we have
=> clean up build.gradle

.github/workflows/build.yml
- Build with Java 8 and 11 for future proofing builds on newer Java releases
- Still release using Java 8
=> Add matrix build for Java 11

build.gradle
- Remove `gradle-nexus-plugin` plugin
- Apply the `com.gradle.plugin-publish` plugin
- Add `sourcesJar`, `testsJar` and `reportsZip` in addition to `docsJar`
- Update POM and add `issueManagement`
- Add more metadata for `bintray`(Jcenter Bintray) and `pluginBundle`(Gradle Plugins)
To verify POM and artifact creation you can run `gradlew publish` and if you want to test `bintray`, you can run `gradlew bintrayUpload` but you need to add `dryrun = true` to `brintray`.
=> Update publishing and remove nexus plugin

src/test/groovy/com/github/benmanes/gradle/versions/DifferentGradleVersionsSpec.groovy, src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy
- Future proof Gradle `OutputFormatterSpec`
- Add more Gradle versions to `DifferentGradleVersionsSpec` - versions from https://gradle.org/releases/
Addresses comments in #467.
=> Future proof gradle OutputFormatterSpec

.github/workflows/deploy.yml, README.md, build.gradle
Migrates off of JCenter and publishes directly to the plugin portal. The github action is run only when a release is created.
=> Publish to the portal directly (fixes #473)

README.md, examples/kotlin/build.gradle.kts
- Use `withType` for lazy access `DependencyUpdatesTask`
- Make `isNonStable` as an extension function for kotlin
=> Optimize kotlin dsl

src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy
`Failed to apply plugin 'com.github.ben-manes.versions'.
> Cannot add task 'dependencyUpdates' as a task with that name already exists.`
when global added plugin via https://github.com/ben-manes/gradle-versions-plugin#using-a-gradle-init-script
=> Fix conflict locally project plugin vs global defined

src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
**Changes Applied**
* dissolved getDisplayableVersion(Dependency) and moved implementation to callers since this is shorter
* changed signature of getDisplayableVersion(DependencyOutdated) to getDisplayableVersion(VersionAvailable) since that parameter type is actually needed in implementation
**Status Quo**
Generating the version string is now done differently for DependencyOutdated than for other Dependency types (...as originally intended, I guess).
=> Issue #508: Refactoring Request: HtmlReporter#getDisplayableVersion(...)

src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy
As widely publicised, [Bintray was sunset in May 2021](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). 
The Bintray links generated by the default HTML report no longer go to the correct location and, as such, should be removed 👍
=> Remove Bintray links from default HTML reporting

README.md
Hey @ben-manes. Unfortunately we decided to stop support for https://github.com/hellofresh/deblibs-gradle-plugin. 
This PR removes a reference to it, so we can avoid redirecting people to deprecated plugin which will be really hard to integrate. If at any point we will decide to update the deblibs plugin and put it back we would let you know. 
Thank you very much!
=> Remove  deblibs-gradle-plugin from the list

src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy, src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
Provides a way to fetch the latest version despite having `resolutionStrategy.failOnDynamicVersions()` active.
Gradle does not expose an official way to disable this check once activated currently. The proposed solution relies on the implementation of the internal `DefaultResolutionStrategy`, but is generally backwards compatible.
resolves #592
=> ignore failOnDynamicVersions() to fetch latest versions

.github/workflows/build.yml, .github/workflows/deploy.yml, settings.gradle.kts
- Only build when based on `opened`, `labeled`, `unlabeled`, `synchronize`
-  Prevents double builds, see https://github.com/ben-manes/gradle-versions-plugin/pull/600
- Update `wrapper-validation-action`
- Update `setup-java`
- Use `temurin`
- Remove `--scan`, allow publishing automatically after builds
@ben-manes
=> update github actions

src/main/groovy/com/github/benmanes/gradle/versions/reporter/HtmlReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/JsonReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/Reporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/reporter/XmlReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/Coordinate.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdates.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesReporter.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/Resolver.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/VersionMapping.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/gradle/GradleUpdateChecker.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionRulesWithCurrent.groovy, src/main/groovy/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.groovy
- Declare the types explicitly. This helps make the codebase more readable and easier to convert to Kotlin in the future.
- Fix formatting
@ben-manes
=> declare explicit types

build.gradle
- Remove `:api` from being publishing to maven
- Merge `:api` class files into final `jar`
To test:
```
gradlew build -x test -s
gradlew publishToMavenLocal -x test -s
cat ~/.m2/repository/com/github/ben-manes/gradle-versions-plugin/0.42.0-SNAPSHOT/gradle-versions-plugin-0.42.0-SNAPSHOT.pom // verify no "api" module
cd examples/groovy
gradle
```
@ben-manes
=> remove api from publshing

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Coordinate.kt
```
/**
* Returns a reason why this dependency should be used, in particular with regards to its version. The dependency report
* will use it to explain why a specific dependency was selected, or why a specific dependency version was used.
*
* @return a reason to use this dependency
*
* @since 4.6
*/
@Nullable
String getReason();
```
`getReason` has been around Gradle 4.6, this plugin supports 5.0+.
@ben-manes
=> remove reflection

README.md
Self-explained. 
Learned that when hitting [this link](https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/reporter/result/Result.groovy)
Thanks for the great plugin!
=> Fixes reference link to Result class on docs

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentFilter.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.kt
Fixes https://github.com/ben-manes/gradle-versions-plugin/issues/673
It looks like the two problems with the Kotlin DSL example are fixed with the next (as suggested in the issue):
**Make ComponentFilter interface functional**
This enables the use of Kotlin's trailing lambda syntax in the `rejectVersionIf` API.
**Make ComponentSelectionWithCurrent.currentVersion not null**
* ComponentSelectionWithCurrent objects are only created in one place and the currentVersion argument passed there is never null, so it's safe to make the property non-null as it effectively never is.
* This also fixes some issues in the Kotlin example, in which the dependencyUpdates task configuration was assumming the `currentVersion` property was not-null.
**Testing**
*Manual*
I have checked that the Kotlin DSL …
=> Fix Kotlin example problems

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt, gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/KotlinDslUsageSpec.groovy, gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/OutputFormatterSpec.groovy
- `groovy.util.XmlSlurper` -> `groovy.xml.XmlSlurper`
- `groovy.util.slurpersupport.GPathResult` -> `groovy.xml.slurpersupport.GPathResult`
- `groovy.util.slurpersupport.NodeChildren` -> `groovy.xml.slurpersupport.NodeChildren`
- Use non deprecated `groovy.xml.XmlParser`
@ben-manes
=> fix XmlSlurper deprecation

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt
In multimodule projects having external constraints but also constraints to own sub projects it makes no sense to check for updates of the these own subprojects (when using checkConstraints=true)
Dependening on the number of own suprojects and also the network performance of the repositories this can give a huge performance boost (for example a few minutes vs. >2 hours in a concrete project)
=> Ignore constraints of own projects ("DefaultProjectDependencyConstraint")

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/PlainTextReporter.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/resolutionstrategy/ComponentSelectionWithCurrent.kt, gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/DependencyUpdatesSpec.groovy
=> Do not use textual 'null' for dependencies without group (#725)

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/VersionsPlugin.kt
Hi,
I noticed that the `dependencyUpdates` task (e.g. when added via global init script) is configured regardless of any task avoidance being used. This is caused by the usage of `tasks.findByName()` that was introduced with https://github.com/ben-manes/gradle-versions-plugin/pull/504 .
Eventually this causes an overhead by using Kotlin reflection in `DependencyUpdatesTask.callIncompatibleWithConfigurationCache`.
A workaround for this is to use `tasks.getNames().contains()`.
Let me know what you think.
Cheers,
Christoph
=> Avoid configuring dependencyUpdates task

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/HtmlReporter.kt
https://github.com/ben-manes/gradle-versions-plugin/issues/748
Old `search.maven.org` domain was replaced with `central.sonatype.com`, the change was reflected in HTML generation code in `HtmlReporter.kt`.
Previous example link wasn't working anymore:
https://search.maven.org/artifact/com.azure/azure-core-http-netty/1.5.4
This URL leads to the correct page instead:
https://central.sonatype.com/artifact/com.azure/azure-core-http-netty/1.5.4
=> Fix broken Sonatype links in HTML reports

README.md, examples/kotlin/build.gradle.kts
Hello! Kotlin's String `toUpperCase()` is deprecated. The new recommended way is to use `uppercase()`.
=> Replace deprecated toUpperCase() kotlin.text calls

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt, gradle-versions-plugin/src/test/groovy/com/github/benmanes/gradle/versions/PluginUpdateDetectionSpec.groovy
This will handle the case of Kotlin plugins (applied to the parentless classpath configuration).
=> Ensure Kotlin dependencies are properly handled when present in a configuration with no parents

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/VersionsPlugin.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt
As described in a prior release and in (gradle/gradle#26672, the insecure parser causes confusing build errors. Thanks @hvisser for the idea to check upfront to give users a clearer error message and point them towards a fix.
=> Fail the build when an insecure XML parser is detected

.github/workflows/build.yml, .github/workflows/dependency-submission.yml, .github/workflows/deploy.yml, build.gradle
- Updates workflows to use Node20-compatible actions where available
- Switches from `gradle/gradle-build-action` to `gradle/actions/setup-gradle`
- Adds a workflow using `gradle/actions/dependency-submission` to generate and upload dependency-graph
- Bumps the version of the 'ktlint' plugin to address reported vulnerability
=> Add dependency-submission workflow and address deprecations/vulnerabilities

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Resolver.kt
This method will be deprecated soon in Gradle for removal in 9.0
The no-argument method will remain at least for the short term
=> Avoid spec-accepting overload of getFirstLevelModuleDependencies

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/VersionsPlugin.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/XmlReporter.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/Coordinate.kt, gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.kt
Fix various warnings such as:
```
w: file:///Users/<>/repo/gradle-versions-plugin/gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/updates/DependencyUpdatesTask.kt:127:66 Java type mismatch: inferred type is 'groovy.lang.Closure<*>', but 'groovy.lang.Closure<kotlin.Any!>' was expected.
```
=> Fix various warnings

gradle/libs.versions.toml
Bump com.squareup.moshi:moshi-kotlin from 1.12.0 to 1.13.0
Slowing upgrading - see https://github.com/ben-manes/gradle-versions-plugin/pull/889
@ben-manes
=> Bump com.squareup.moshi:moshi-kotlin from 1.12.0 to 1.13.0

gradle-versions-plugin/src/main/kotlin/com/github/benmanes/gradle/versions/reporter/HtmlReporter.kt
Backslashes are not interpreted in raw strings.
Fixes #933
=> Fix HTML report

README.md
At some point this changed. I don't know when or why, but I know using `./gradlew publishToMavenLocal` worked for me.
=> Use correct install command

README.md
Add known issues section and workaround for configuration cache incompatibility.
```
5 problems were found storing the configuration cache, 4 of which seem unique.
- Task `:app:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: cannot deserialize Gradle script object references as these are not supported with the configuration cache.
See https://docs.gradle.org/8.14.3/userguide/configuration_cache.html#config_cache:requirements:disallowed_types
- Task `:app:dependencyUpdates` of type `com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask`: cannot serialize Gradle script object references as these are not supported with the configuration cache.
See https://docs.gradle.org/8.14.3/userguide/configuration_cache.html#config_cache:requirem …
```
=> Update README.md for upstream Gradle issue workaround
